"""change books

Revision ID: 53814bb6a46c
Revises: 79a8584dc6f9
Create Date: 2023-04-23 01:58:12.955472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53814bb6a46c'
down_revision = '79a8584dc6f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('noms', sa.String(), nullable=True))
    op.add_column('books', sa.Column('wins', sa.String(), nullable=True))
    op.drop_column('books', 'awards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('awards', sa.VARCHAR(), nullable=True))
    op.drop_column('books', 'wins')
    op.drop_column('books', 'noms')
    # ### end Alembic commands ###
