"""change books + users

Revision ID: 62f591b85478
Revises: 83ebfd24d01f
Create Date: 2023-04-23 23:10:59.444959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f591b85478'
down_revision = '83ebfd24d01f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('num_of_readers', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('favorite', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('favorite_books', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_books')
    op.drop_column('books', 'favorite')
    op.drop_column('books', 'num_of_readers')
    # ### end Alembic commands ###
