"""change books

Revision ID: 671ed155bb65
Revises: 53814bb6a46c
Create Date: 2023-04-23 02:36:50.607241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671ed155bb65'
down_revision = '53814bb6a46c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('note', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
