"""change books

Revision ID: 79a8584dc6f9
Revises: 
Create Date: 2023-04-23 01:44:37.566004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a8584dc6f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('work_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('work_year_of_write', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('awards', sa.String(), nullable=True))
    op.add_column('books', sa.Column('similars', sa.String(), nullable=True))
    op.add_column('books', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'note')
    op.drop_column('books', 'similars')
    op.drop_column('books', 'awards')
    op.drop_column('books', 'work_year_of_write')
    op.drop_column('books', 'work_year')
    # ### end Alembic commands ###
