"""add info.py and images.py

Revision ID: 9315508b6fef
Revises: 49b216a2afbe
Create Date: 2023-04-19 20:35:21.925098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9315508b6fef'
down_revision = '49b216a2afbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('image', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'info', ['info'], ['id'])
    op.create_foreign_key(None, 'books', 'images', ['image'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'image')
    op.drop_table('info')
    op.drop_table('images')
    # ### end Alembic commands ###
