"""add cnt_comments

Revision ID: 93f21ba27f36
Revises: 80a436c29613
Create Date: 2023-04-24 03:12:26.905493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f21ba27f36'
down_revision = '80a436c29613'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comments')
    # ### end Alembic commands ###
